SDL_PROC(void, glGenFramebuffers, (GLsizei n, GLuint* ids))
SDL_PROC(void, glBindFramebuffer, (GLenum target, GLuint framebuffer))

SDL_PROC(void, glGenRenderbuffers, (GLsizei n, GLuint* buffers))
SDL_PROC(void, glBindRenderbuffer, (GLenum target, GLuint buffer))
SDL_PROC(void, glRenderbufferStorage, (GLenum target, GLenum format, GLsizei width, GLsizei height))

SDL_PROC(void, glFramebufferRenderbuffer, (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer))
SDL_PROC(void, glFramebufferTexture2D, (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level))
SDL_PROC(GLenum, glCheckFramebufferStatus, (GLenum target))
SDL_PROC(void, glDeleteFramebuffers, (GLsizei n, GLuint *framebuffers))
SDL_PROC(void, glDeleteRenderbuffers, (GLsizei n, GLuint *buffers))
SDL_PROC(void, glGenerateMipmap, (GLenum target))
SDL_PROC(GLboolean, glIsRenderbuffer, (GLuint renderbuffer))
SDL_PROC(void, glGetRenderbufferParameteriv, (GLenum target, GLenum pname, GLint *params))
SDL_PROC(void, glRenderbufferStorageMultisample, (GLenum target, GLuint samples, GLenum format, GLsizei width, GLsizei height))
SDL_PROC(void, glTexImage2DMultisample, (GLenum target, GLsizei samples, GLint internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations))
SDL_PROC(void, glBlitFramebuffer, (GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter))
//SDL_PROC(, gl, ())
